
services:
  # Backend service
  backend:
    build:
      context: ./Backend-Course-Blogging-Application-main
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - myapp-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./Frontend-blogging
      dockerfile: Dockerfile
    image: ${FRONTEND_IMAGE}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - myapp-network
    restart: unless-stopped

networks:
  myapp-network:
    driver: bridge
